#!/bin/sh

######################################################
## A small utility that informs about SHORK 486's   ##
## capabilities                                     ##
######################################################
## Kali (sharktastica.co.uk)                        ##
######################################################



DROPBEAR_PRESENT=true
FILE_PRESENT=true
EMACS_PRESENT=true
GIT_PRESENT=true
LSUSB_PRESENT=true
NANO_PRESENT=true
SHORKMAP_PRESENT=true
SHORKRES_PRESENT=true
TNFTP_PRESENT=true

if [ ! -x /usr/bin/scp ]; then
    DROPBEAR_PRESENT=false
fi
if [ ! -x /usr/bin/ssh ]; then
    DROPBEAR_PRESENT=false
fi
if [ ! -x /usr/bin/file ]; then
    FILE_PRESENT=false
fi
if [ ! -x /usr/bin/mg ]; then
    EMACS_PRESENT=false
fi
if [ ! -x /usr/bin/git ]; then
    GIT_PRESENT=false
fi
if [ ! -x /usr/bin/lsusb ]; then
    LSUSB_PRESENT=false
fi
if [ ! -x /usr/bin/nano ]; then
    NANO_PRESENT=false
fi
if [ ! -x /usr/bin/shorkmap ]; then
    SHORKMAP_PRESENT=false
fi
if [ ! -x /usr/bin/shorkres ]; then
    SHORKRES_PRESENT=false
fi
if [ ! -x /usr/bin/ftp ]; then
    TNFTP_PRESENT=false
fi

WIDTH=$(stty size 2>/dev/null | cut -d' ' -f2)



print_commands()
{
    OUTPUT="General
-------
awk, basename, cat, chmod, chown, chroot, cp, cut, dirname, expr, file, find, fold, grep, gzip, head, less, ln, loadkmap, ls, man, mkdir, mknod, mount, mv, paste, printf, pwd, readlink, rev, rm, rmdir, sed, seq, showkey, stat, sync, tar, tee, test, touch, tr, umount, unzip, whereis, which, xz

Editors & development tools
---------------------------
ed, emacs, git, nano, vi

System & processes
------------------
beep, blkid, clear, crontab, date, df, dmesg, free, halt, hostname, kill, losetup, lsblk, lspci, lsusb, nice, nohup, nproc, pkill, sleep, stty, swapoff, swapon, top, uname, whoami

Networking & remote access
--------------------------
ftp, ftpget, ftpput, ifconfig, ping, route, scp, ssh, udhcpc, wget

SHORK utilities
---------------
shorkcol, shorkfetch, shorkhelp, shorkmap, shorkoff, shorkres"

    if ! $DROPBEAR_PRESENT; then
       OUTPUT=$(echo "$OUTPUT" |  sed -e "s|, scp, ssh||g")
    fi
    if ! $FILE_PRESENT; then
       OUTPUT=$(echo "$OUTPUT" |  sed -e "s|, file||g")
    fi
    if ! $EMACS_PRESENT; then
        OUTPUT=$(echo "$OUTPUT" | sed -e "s|, emacs||g")
    fi
    if ! $GIT_PRESENT; then
        OUTPUT=$(echo "$OUTPUT" | sed -e "s|, git||g")
    fi
    if ! $LSUSB_PRESENT; then
        OUTPUT=$(echo "$OUTPUT" | sed -e "s|lsusb, ||g")
    fi
    if ! $NANO_PRESENT; then
        OUTPUT=$(echo "$OUTPUT" | sed -e "s|, nano||g")
    fi
    if ! $SHORKMAP_PRESENT; then
        OUTPUT=$(echo "$OUTPUT" | sed -e "s|, shorkmap||g")
    fi
    if ! $SHORKRES_PRESENT; then
        OUTPUT=$(echo "$OUTPUT" | sed -e "s|, shorkres||g")
    fi
    if ! $TNFTP_PRESENT; then
        OUTPUT=$(echo "$OUTPUT" | sed -e "s|ftp, ||g")
    fi

    echo "$OUTPUT" | fold -s -w "$WIDTH"
}

print_emacs_hints()
{
cat <<'EOF'
Emacs (Mg) cheatsheet
---------------------

C = Ctrl                                    M = Alt

Exit:                       C-x C-c         Open file/new buffer:       C-x C-f
Save current buffer:        C-x C-s         Save all buffers:           C-x s

Split window:               C-x 2           Enlarge window:             C-x ^
Switch windows:             C-x o           Close current window:       C-x 0
Close other windows:        C-x 1

Go to line:                 C-x g           Undo:                       C-_
Search (forwards):          C-s             Search (backwards):         C-r
Find and replace:           M-%             Reformat (fit to line):     M-q
EOF
}

print_git_commands()
{
    OUTPUT="Supported Git commands
----------------------

add, blame, branch, checkout, cherry-pick, clean, clone, commit, config, diff, fetch, init, log, merge, mv, pull, push, rebase, reflog, remote, reset, restore, rm, show, stash, status, switch, tag"

    echo "$OUTPUT" | fold -s -w "$WIDTH"
}

print_intro()
{
    OUTPUT="What is @NAME@?
------------------
@NAME@ is a minimal Linux distribution designed with 486SX compatibility and vintage PCs in mind. It focuses on being small (no more than 72MiB) whilst still providing a practical command set and networking utilities. It was inspired by FLOPPINUX, but expanded beyond floppy diskette limits.

Getting started with @NAME@
------------------------------
1. Set your keyboard's layout with shorkmap.
2. Pick a font colour for terminal text with shorkcol.
3. (If compatible) Change your display's resolution with shorkres. A reboot is required afterwards.
4. Set your computer's name by editing /etc/hostname. A reboot is required afterwards, or you can run:
      hostname "$(cat /etc/hostname)"
5. (If applicable) Test your network connection with ping. For example:
      ping sharktastica.co.uk
6. Run shorkfetch to see a quick overview of your system and environment.
7. Check shorkhelp's other options to learn about all available commands and other @NAME@ utilities.
8. When you are finished using @NAME@, run shorkoff to safely bring your system to a halt."

    echo "$OUTPUT" | fold -s -w "$WIDTH"
}

print_utilities()
{
    OUTPUT="SHORK utilities
---------------

shorkcol - Persistently changes the terminal's foreground (text) colour. This utility takes one argument (a colour name); running it without an argument shows a list of possible colours.

shorkfetch - Displays basic system and environment information. Similar to fastfetch, neofetch, etc. This utility takes no arguments.

shorkhelp - Provides help with using @NAME@ via command lists, guides and cheatsheets. This utility requires the use of one of five parameters.

shorkmap - Persistently changes the system's keymap. This utility takes one argument (a keymap name); running it without an argument shows a list of possible keymaps.

shorkoff - Brings the system to a halt and syncs the write cache, allowing the computer to be safely turned off. Similar to poweroff or shutdown -h. This utility takes no arguments.

shorkres - Persistently changes the system's display resolution (provided the hardware is compatible). This utility takes one argument (a resolution name); running it without an argument shows a list of possible resolution names."

    if ! $SHORKMAP_PRESENT; then
        OUTPUT=$(echo "$OUTPUT" | awk '/^shorkmap -/ {f=1; next} f && /^$/ {f=0; next} !f')
    fi

    if ! $SHORKRES_PRESENT; then
        OUTPUT=$(echo "$OUTPUT" | awk '/^shorkres -/ {f=1; next} f && /^$/ {f=0; next} !f')
    fi

    echo "$OUTPUT" | fold -s -w "$WIDTH"
}



for arg in "$@"; do
    case "$arg" in
        --commands)
            clear
            print_commands
            return 1
            ;;
        --emacs)
            if $EMACS_PRESENT; then
                clear
                print_emacs_hints
                return 1
            fi
            ;;
        --git)
            if $GIT_PRESENT; then
                clear
                print_git_commands
                return 1
            fi
            ;;
        --intro)
            clear
            print_intro
            return 1
            ;;
        --shorkutils)
            clear
            print_utilities
            return 1
            ;;
    esac
done

CMDS="--commands | --emacs | --git | --intro | --shorkutils"

if ! $EMACS_PRESENT; then
    CMDS=$(echo "$CMDS" | sed -E 's/--emacs \| //g; s/ \| --emacs//g; s/--emacs//g')
fi
if ! $GIT_PRESENT; then
    CMDS=$(echo "$CMDS" | sed -E 's/--git \| //g; s/ \| --git//g; s/--git//g')
fi

printf "Displays help and reference information for using @NAME@ and its built-in tools.\n\n" | fold -s -w "$WIDTH"
echo "Usage: shorkhelp {$CMDS}" | fold -s -w "$WIDTH"
exit 1
