#!/bin/sh

# A small utility for persistent changing the terminal
# foreground (font) colour
# Kali (sharktastica.co.uk)



set -e

if [ $# -ne 1 ]; then
    echo "Usage: shorkcol {blue|cyan|green|magenta|red|white|yellow}"
    exit 1
fi

case "$1" in
    blue)     COL="0;1;34" ;;
    cyan)     COL="0;36" ;;
    green)    COL="0;32" ;;
    magenta)  COL="0;35" ;;
    red)      COL="0;31" ;;
    white)    COL="0;37" ;;
    yellow)   COL="0;1;33" ;;
    *)
        echo "Invalid colour: $1"
        exit 1
        ;;
esac



sed -i "s/\\\\033\[[0-9;]*m/\\\\033[${COL}m/g" /etc/profile
sed -i "s/\\\\033\[[0-9;]*m/\\\\033[${COL}m/g" /etc/init.d/rc
sed -i 's|sgr0=\\E\[0m\\E\[[0-9;]*m|sgr0=\\E[0m\\E['"$COL"'m|' /usr/share/terminfo/src/terminfo.src
tic -x -1 -o /usr/share/terminfo /usr/share/terminfo/src/terminfo.src

kill -TERM "$PPID"
