#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mdev -s
ln -s /proc/mounts /etc/mtab
mkdir -p /mnt /home
mount -t msdos -o rw /dev/fd0 /mnt
mkdir -p /mnt/data
mount --bind /mnt/data /home

[ -r /etc/hostname ] && hostname "$(cat /etc/hostname)"

export TERM=linux
export TERMINFO=/usr/share/terminfo
export HOME=/home

# Make terminal font green & show current dir
export PS1='\033[32m\033[40m\w$ '
printf '\033[32m\033[40m'

clear
cat welcome
cd /home

while true; do
    /bin/sh -i
done
