#!/bin/sh

######################################################
## System init script executed during boot that     ##
## mounts core file systems, ensures essential      ##
## device nodes exist, sets hostname and            ##
## environment, configures basic networking,        ##
## displays a welcome message, and begins a sync    ##
## loop to help prevent data loss on hard reboots   ##
######################################################
## Kali (sharktastica.co.uk)                        ##
######################################################



# Mount core file systems
mount -t proc  proc  /proc
mount -t sysfs sysfs /sys

# Required device nodes
[ -c /dev/tty ]  || mknod -m 666 /dev/tty  c 5 0
[ -c /dev/tty0 ] || mknod -m 620 /dev/tty0 c 4 0
[ -c /dev/tty1 ] || mknod -m 620 /dev/tty1 c 4 1

[ -r /etc/hostname ] && hostname "$(cat /etc/hostname)"

# Load persistent keymap (if present)
if [ -f /etc/keymap ]; then
    KM="$(cat /etc/keymap)"
    if [ -f "/usr/share/keymaps/$KM.kmap.bin" ]; then
        loadkmap < "/usr/share/keymaps/$KM.kmap.bin"
    fi
fi

export ENV=/etc/profile

# Make terminal font green & show current dir
printf '\033[37m\033[40m'

# Set up networking
if [ -d /sys/class/net/eth0 ] && [ -e /sys/class/net/eth0/device ]; then
    ifconfig eth0 up
    if ifconfig eth0 2>/dev/null | grep -q "UP"; then
        udhcpc -i eth0 -n -t 3 -T 2 -s /usr/share/udhcpc/default.script > /dev/null 2>&1 &
    fi
fi

# Set up PC speaker
modprobe pcspkr 2>/dev/null || true

# Show welcome banner
clear

COLS=$(stty size 2>/dev/null | awk '{print $2}')
BANNER=""

if [ "$COLS" -ge 128 ] && [ -f banners/welcome-128 ]; then
    BANNER="banners/welcome-128"
elif [ "$COLS" -ge 100 ] && [ -f banners/welcome-100 ]; then
    BANNER="banners/welcome-100"
elif [ "$COLS" -ge 80 ] && [ -f banners/welcome-80 ]; then
    BANNER="banners/welcome-80"
fi

if [ -n "$BANNER" ]; then
    printf "\x1b[37;44m"
    cat "$BANNER"
    printf "\x1b[0m"
fi

printf "\n\n"

# Show welcome tip (if first boot)
# First‑boot hint
if [ ! -f /etc/.past_first_boot ]; then
    printf "Welcome! If this is your first time using @NAME@, please check out \033[32mshorkhelp\033[0m!"
    echo "1" > /etc/.past_first_boot
    printf "\n\n"
fi

# Periodic sync write cache to help ensure files aren't lost after hard reboot
# User should IDEALLY use shorkoff before hard turning off the host, though!
(
    while true; do
        sleep 10
        sync
    done
) &
