#!/bin/sh

######################################################
## A small utility that informs about SHORK 486's   ##
## capabilities                                     ##
######################################################
## Kali (sharktastica.co.uk)                        ##
######################################################



echo "Basic commands & utilities
--------------------------
awk, basename, beep, cat, chmod, chown, chroot, clear, cp, crontab, cut, date,
echo, find, free, ftpget, ftpput, grep, hostname, ifconfig, kill, less,
loadfont, loadkmap, ls, man, mkdir, mknod, mount, mv, nohup, ping, pkill,
printf, pwd, readlink, rm, rmdir, route, sed, showkey, sleep, sync, tee, test,
top, touch, tr, udhcpc, umount, uname, vi, wget, which

SHORK 486 utilities
--------------------
shorkcol, shorkfetch, shorkhelp, shorkmap

Bundled software
----------------
ftp, git, nano, scp, ssh

Supported Git commands
----------------------
add, blame, branch, checkout, cherry-pick, clean, clone, commit, config, diff,
fetch, init, log, merge, mv, pull, push, rebase, reflog, remote, reset,
restore, rm, show, stash, status, switch, tag
"
