#!/bin/sh

######################################################
## A small utility that calls sync to help prevent  ##
## data loss from any unwritten cache and halts the ##
## CPU ready for SHORK 486 to be turned off.        ##
######################################################
## Kali (sharktastica.co.uk)                        ##
######################################################



cd /
clear

COLS=$(stty size 2>/dev/null | awk '{print $2}')
BANNER=""

if [ "$COLS" -ge 128 ] && [ -f banners/goodbye-128 ]; then
    BANNER="banners/goodbye-128"
elif [ "$COLS" -ge 100 ] && [ -f banners/goodbye-100 ]; then
    BANNER="banners/goodbye-100"
elif [ "$COLS" -ge 80 ] && [ -f banners/goodbye-80 ]; then
    BANNER="banners/goodbye-80"
fi

if [ -n "$BANNER" ]; then
    printf "\033[38;5;208m"
    cat "$BANNER"
    printf "\033[0m"
fi

sync
sync
mount -o remount,ro /
halt -f
